name: angel3_security
version: 6.0.1
description: Angel3 infrastructure for improving security, rate limiting, and more
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/security
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  angel3_framework: ^6.0.0
  crypto: ^3.0.1
dev_dependencies: 
  angel3_auth: ^6.0.0
  angel3_production: ^6.0.0
  angel3_redis: ^6.0.0
  angel3_test: ^6.0.0
  angel3_validate: ^6.0.0
  belatuk_pretty_logging: ^4.0.0
  test: ^1.21.0
  lints: ^1.0.0
#dependency_overrides:
#  angel3_auth:
#    path: ../auth
