name: angel3_security
version: 3.0.0
description: Angel infrastructure for improving security, rate limiting, and more
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/security
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel3_framework: ^4.0.0
  crypto: ^3.0.1
dev_dependencies: 
  angel3_auth: ^4.0.0
  angel3_production: ^3.0.0
  angel3_redis: ^2.0.0
  angel3_test: ^4.0.0
  angel3_validate: ^4.0.0
  angel3_pretty_logging: ^3.0.0
  pedantic: ^1.11.1
  test: ^1.17.8
