name: angel3_security
version: 3.1.0
description: Angel3 infrastructure for improving security, rate limiting, and more
homepage: https://github.com/dukefirehawk/angel/tree/master/packages/security
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel3_framework: ^4.2.0
  crypto: ^3.0.1
dev_dependencies: 
  angel3_auth: ^4.0.0
  angel3_production: ^3.1.0
  angel3_redis: ^2.0.0
  angel3_test: ^4.0.0
  angel3_validate: ^4.0.0
  belatuk_pretty_logging: ^4.0.0
  test: ^1.17.5
  lints: ^1.0.0
