name: angel3_client
version: 4.0.1
description: A browser, mobile and command line based client that supports querying Angel3 servers
homepage: https://angel3-framework.web.app/
respository: https://github.com/dukefirehawk/angel/tree/angel3/packages/client
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_http_exception: ^3.0.0
  angel3_json_god: ^4.0.0
  collection: ^1.15.0
  http: ^0.13.1
  meta: ^1.3.0
  path: ^1.8.0
dev_dependencies:
  angel3_framework: ^4.0.0
  angel3_model: ^3.0.0
  angel3_mock_request: ^2.0.0
  angel3_container: ^3.0.0
  async: ^2.6.1
  build_runner: ^1.12.2
  build_web_compilers: ^2.16.5
  pedantic: ^1.11.0
  test: ^1.17.4
