name: angel_client
version: 4.0.0
description: Support for querying Angel servers in the browser, Flutter, and command-line.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_client
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel_http_exception:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/http_exception
  collection: ^1.15.0
  http: ^0.13.1
  json_god:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/json_god
  #dart_json_mapper: ^1.7.0
  meta: ^1.3.0
  path: ^1.8.0
dev_dependencies:
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  angel_model:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/model
  async: ^2.5.0
  build_runner: ^1.12.2
  build_web_compilers: ^2.16.5
  mock_request:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/mock_request
  pedantic: ^1.11.0
  test: ^1.16.8
