name: user_agent_analyzer
version: 3.0.1
description: A library to identify the type of devices and web browsers based on User-Agent string.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/user_agent/user_agent
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.17.8
  pedantic: ^1.11.1
