name: user_agent_analyzer
version: 3.0.0
description: A library that identify the type of devices and web browsers based on User-Agent.
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.17.8
  pedantic: ^1.11.1
