name: angel3_html_builder
description: Build HTML AST's and render them to HTML. This can be used as an internal DSL, i.e. for a templating engine.
version: 2.0.3
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/html_builder
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0
dev_dependencies:
  html: ^0.15.0
  test: ^1.17.4
  pedantic: ^1.11.0