name: angel3_route
version: 5.0.0
description: A powerful, isomorphic routing library for Dart. It is mainly used in the Angel framework, but can be used in Flutter and on the Web.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/route
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_combinator: ^2.0.0
  string_scanner: ^1.1.0
  path: ^1.8.0
dev_dependencies:
  build_runner: ^1.12.2
  build_web_compilers: ^2.16.5
  http: ^0.13.3
  pedantic: ^1.11.0
  test: ^1.17.4