name: angel3_jael
version: 4.2.1
description: Angel support for the Jael templating engine, similar to Blade or Liquid.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/jael/angel_jael
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  belatuk_code_buffer: ^3.0.0
  belatuk_symbol_table: ^3.0.0
  jael3: ^4.2.0
  jael3_preprocessor: ^4.2.0
  file: ^6.0.0
  logging: ^1.0.1
dev_dependencies:
  angel3_test: ^4.0.0
  html: ^0.15.0
  test: ^1.17.3
  lints: ^1.0.0
#dependency_overrides:
#  jael3:
#    path: ../jael
#  jael3_preprocessor:
#    path: ../jael_preprocessor
