name: angel3_sync
version: 4.1.1
description: Easily synchronize and scale WebSockets using belatuk_pub_sub in Angel3.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/sync
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  angel3_websocket: ^4.1.0
  belatuk_pub_sub: ^4.0.0
  stream_channel: ^2.1.0
dev_dependencies:
  angel3_test: ^4.1.0
  test: ^1.17.5
  lints: ^1.0.0
#dependency_overrides:
#  angel3_websocket:
#    path: ../websocket
