name: angel_orm_generator
version: 1.0.0-alpha+6
description: Code generators for Angel's ORM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_orm: ^1.0.0-alpha
  angel_serialize_generator: ^2.0.0
  code_builder: ^3.0.0
  inflection: ^0.4.1
  meta: ^1.0.0
  recase: ^1.0.0
dev_dependencies:
  angel_diagnostics: ^1.0.0
  angel_framework: ^1.0.0
  angel_migration: ^1.0.0-alpha
  angel_test: ^1.0.0
  build_runner: ^0.7.0
  test: ^0.12.0
dependency_overrides:
  angel_orm:
    path: ../angel_orm
