name: angel_orm_generator
version: 2.0.0-dev
description: Code generators for Angel's ORM. Generates query builder classes.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_orm: ^2.0.0-dev
  angel_serialize_generator: ^2.0.0
  build: ">=0.12.0 <2.0.0"
  build_config: ^0.3.0
  code_builder: ^3.0.0
  inflection:
    git:
      url: https://github.com/thosakwe/dart-inflection.git
      ref: dart2
  meta: ^1.0.0
  path: ^1.0.0
  recase: ^2.0.0
  source_gen: ^0.9.0
dev_dependencies:
  angel_framework: ^2.0.0-alpha
  #angel_migration: ^1.0.0-alpha
  #angel_test: ^1.0.0
  build_runner: ^1.0.0
  collection: ^1.0.0
  postgres: ^1.0.0
  test: ^1.0.0
