name: angel3_hot
version: 4.3.0
description: Supports hot reloading/hot code push of Angel3 servers on file changes.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/hot
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  angel3_websocket: ^4.1.0
  belatuk_html_builder: ^3.0.0
  charcode: ^1.2.0
  glob: ^2.0.1
  io: ^1.0.0
  path: ^1.8.0
  vm_service: ^8.1.0
  watcher: ^1.0.0
dev_dependencies:
  http: ^0.13.2
  logging: ^1.0.1
  lints: ^1.0.0
#dependency_overrides:
#  angel3_websocket:
#    path: ../websocket
 