name: angel_framework
version: 4.0.0
description: A high-powered HTTP server with dependency injection, routing and much more.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_framework
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  angel_container:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/container/angel_container
  angel_http_exception:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/http_exception
  angel_model:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/model
  angel_route:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/route
  charcode: ^1.2.0
  combinator:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/combinator
  file: ^6.1.0
  http_parser: ^4.0.0
  http_server: ^1.0.0
  http2: ^2.0.0
  logging: ^1.0.0
  matcher: ^0.12.10
  merge_map:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/merge_map
  meta: ^1.3.0
  mime: ^1.0.0
  mock_request:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/mock_request
  path: ^1.8.0
  # pedantic: ^1.0.0
  #quiver_hashcode: ^3.0.0+1
  quiver: ^3.0.0
  recase: ^4.0.0-nullsafety.0
  stack_trace: ^1.10.0
  string_scanner: ^1.1.0
  tuple: ^2.0.0
  uuid: ^3.0.1
dev_dependencies:
  http: ^0.13.1
  io: ^1.0.0
  #pretty_logging: ^1.0.0
  test: ^1.16.8

