name: angel_framework
version: 3.0.0
description: A high-powered HTTP server with dependency injection, routing and much more.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_framework
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  angel_container:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/container/angel_container
  angel_http_exception:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/http_exception
  angel_model:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/model
  angel_route:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/route
  charcode: ^1.0.0
  combinator: ^1.0.0
  file: ^6.1.0
  http_parser: ^4.0.0
  http_server: ^0.9.0
  http2: ^2.0.0
  logging: ^1.0.0
  matcher: ^0.12.0
  merge_map: ^1.0.0
  meta: ^1.0.0
  mime: ^0.9.0
  mock_request: ^1.0.0
  path: ^1.0.0
  # pedantic: ^1.0.0
  quiver_hashcode: ^2.0.0
  recase: ^3.0.1
  stack_trace: ^1.0.0
  string_scanner: ^1.0.0
  tuple: ^1.0.3
  uuid: ^3.0.1
dev_dependencies:
  http: ^0.13.0
  io: ^1.0.0
  #pretty_logging: ^1.0.0
  test: ^1.15.7

