name: angel3_framework
version: 4.0.2
description: A high-powered HTTP server with dependency injection, routing and much more.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/framework
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_container: ^3.0.0
  angel3_http_exception: ^3.0.0
  angel3_model: ^3.0.0
  angel3_route: ^5.0.0
  angel3_combinator: ^2.0.0
  angel3_merge_map: ^2.0.0
  angel3_mock_request: ^2.0.0
  charcode: ^1.2.0
  file: ^6.1.0
  http_parser: ^4.0.0
  http_server: ^1.0.0
  http2: ^2.0.0
  logging: ^1.0.0
  matcher: ^0.12.10
  meta: ^1.3.0
  mime: ^1.0.0
  path: ^1.8.0
  quiver: ^3.0.1
  recase: ^4.0.0
  stack_trace: ^1.10.0
  string_scanner: ^1.1.0
  tuple: ^2.0.0
  uuid: ^3.0.1
  collection: ^1.15.0
dev_dependencies:
  http: ^0.13.1
  io: ^1.0.0
  test: ^1.17.4
  pedantic: ^1.11.0
