name: angel3_user_agent
version: 3.0.0
description: Angel3 middleware to parse and inject a User Agent object into requests.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/user_agent/angel_user_agent
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.0.0
  user_agent_analyzer: ^3.0.0
  pedantic: ^1.11.1