name: performance_tool
version: 1.0.0
description: Angel3 performance testing tool
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
published_to: none
dependencies:
  http: ^0.13.4
dev_dependencies:
  lints: ^1.0.0