name: angel_client
version: 1.1.0+1
description: Client library for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_client
environment:
  sdk: ">=1.21.0"
dependencies:
  angel_http_exception: ^1.0.0
  collection: ^1.0.0
  http: ">= 0.11.3 < 0.12.0"
  json_god: ">=2.0.0-beta <3.0.0"
  merge_map: ">=1.0.0 <2.0.0"
dev_dependencies:
  angel_framework: ^1.1.0-alpha
  angel_model: ^1.0.0
  mock_request: ^1.0.0
  test: ">= 0.12.13 < 0.13.0"
