name: angel_auth
description: A complete authentication plugin for Angel.
version: 1.0.0-dev+10
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_auth
dependencies:
  angel_framework: ">=1.0.0-dev <2.0.0"
  crypto: ">=2.0.0 <3.0.0"
  oauth2: ">= 1.0.2 < 2.0.0"
dev_dependencies:
  http: ">= 0.11.3 < 0.12.0"
  test: ">= 0.12.13 < 0.13.0"