name: angel_hot
description: Supports hot reloading of Angel servers on file changes.
version: 1.1.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/hot
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.1.0-alpha
  angel_websocket: ^1.1.0-alpha
  html_builder: ^1.0.0
  vm_service_lib: 0.3.5
dev_dependencies:
    angel_test: ^1.0.0
    http: ^0.11.3
    test: ^0.12.15