name: angel_oauth2
author: Tobe O <thosakwe@gmail.com>
description: angel_auth strategy for in-house OAuth2 login.
homepage: https://github.com/thosakwe/oauth2_server.git
version: 1.0.0-alpha
environment:
  sdk: ">=1.19.0"
dependencies: 
  angel_auth: ^1.1.0-alpha
dev_dependencies: 
  angel_test: ^1.1.0-alpha
  oauth2: ^1.0.0
  test: ^0.12.0
