name: angel_html
version: 1.0.0
description: Easily render html_builder AST's as responses in Angel.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/html_builder
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
  html_builder: ^1.0.0
dev_dependencies:
  angel_test: ^1.0.0
  html: ^0.13.2
  test: ^0.12.0