name: angel_http_exception
version: 1.0.0
description: Angel's HTTP exception class.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/http_exception
environment:
  sdk: ">=1.19.0"