name: angel_framework
version: 0.0.0-dev.19
description: Core libraries for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_framework
dependencies:
  body_parser: ^1.0.0-dev
  json_god: ^1.0.0
  merge_map: ^1.0.0
  mime: ^0.9.3
dev_dependencies:
  http: ^0.11.3
  test: ^0.12.13