name: angel_static
description: Static server middleware for Angel.
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/static
author: Tobe O <thosakwe@gmail.com>
version: 1.3.0-alpha+2
dependencies:
  angel_framework: ^1.1.0-alpha
  file: ^2.0.0
  intl: ">=0.0.0 <1.0.0"
  mime: ^0.9.3
  path: ^1.4.2
dev_dependencies:
  angel_test: ^1.1.0-alpha
  http: ^0.11.3
  mustache4dart: ^1.1.0
  test: ^0.12.13
