name: angel_configuration
description: Automatic YAML configuration loader for Angel.
version: 1.1.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_configuration
environment:
  sdk: ">=1.19.0"
dependencies:
  analyzer: ">=0.28.1 <1.0.0"
  angel_framework: ^1.1.0-alpha
  barback: ^0.15.2
  dotenv: ^0.1.0
  file: ^2.0.0
  merge_map: ^1.0.0
  yaml: ^2.0.0
dev_dependencies:
  test: ^0.12.0
