author: "Tobe O <thosakwe@gmail.com>"
description: "Angel middleware designed to enhance application security by patching common Web security holes."
homepage: "https://github.com/angel-dart/security"
name: "angel_security"
version: "1.1.0"
dependencies: 
  angel_framework: "^1.1.0"
dev_dependencies: 
  angel_auth: "^1.1.0"
  angel_test: "^1.1.0"
  angel_validate: "^1.0.0"
  console: "^2.2.4"
  test: "^0.12.0"
environment: 
  sdk: ">=1.19.0"
