name: angel_framework
version: 1.0.0-dev.36
description: Core libraries for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_framework
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_route: ^1.0.0-dev
  body_parser: ^1.0.0-dev
  container: ^0.1.2
  json_god: ^2.0.0-beta
  merge_map: ^1.0.0
  mime: ^0.9.3
dev_dependencies:
  http: ^0.11.3
  test: ^0.12.13
