name: angel_oauth2
author: Tobe O <thosakwe@gmail.com>
description: angel_auth strategy for in-house OAuth2 login.
homepage: https://github.com/angel-dart/oauth2.git
version: 1.0.0+1
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies: 
  angel_framework: ^1.0.0-dev
  angel_http_exception: ^1.0.0
  dart2_constant: ^1.0.0
dev_dependencies: 
  angel_test: ^1.1.0-alpha
  oauth2: ^1.0.0
  test: ^0.12.0
