name: angel_static
description: Static server middleware for Angel.
environment:
  sdk: ">=1.8.0 <3.0.0"
homepage: https://github.com/angel-dart/static
author: Tobe O <thosakwe@gmail.com>
version: 2.0.0-alpha
dependencies:
  angel_framework: ^2.0.0-alpha
  file: ^5.0.0
  intl: ">=0.0.0 <1.0.0"
  mime: ^0.9.3
  path: ^1.4.2
dev_dependencies:
  angel_test: ^2.0.0-alpha
  http: ^0.11.3
  mustache4dart: ^3.0.0-dev.0.0
  test: ^1.0.0
