name: angel_orm
version: 0.0.0
description: Source-generated ORM for use with the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_mongo
dependencies:
  angel_framework: ">=1.0.0-dev < 2.0.0"
  code_builder: ^1.0.0
  id: ^1.0.0
  inflection: ^0.4.1
  intl: ^0.15.1
  query_builder_sql: ^1.0.0-alpha
  recase: ^1.0.0
  source_gen: ^0.5.8
dev_dependencies:
  angel_diagnostics: ">=1.0.0 <2.0.0"
  angel_serialize:
    path: ../serialize
  angel_test: ">=1.0.0 <2.0.0"
  build_runner: ^0.3.0
  http: ">= 0.11.3 < 0.12.0"
  postgres: ">=0.9.5 <1.0.0"
  test: ">= 0.12.13 < 0.13.0"