name: angel_file_service
version: 1.0.0
description: Angel service that persists data to a file on disk.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/file_service
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0-dev
  pool: ^1.0.0