name: angel_websocket
description: WebSocket plugin for Angel
environment:
  sdk: ">=1.19.0"
version: 1.0.0-dev+10
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_websocket
dependencies:
  angel_auth: "^1.0.0-dev"
  angel_client: "^1.0.0-dev"
  angel_framework: "^1.0.0-dev"
  uuid: "^0.5.3"
  web_socket_channel: "^1.0.0"
dev_dependencies:
  angel_diagnostics: "^1.0.0-dev"
  http: "^0.11.3"
  test: "^0.12.15"
