name: angel_configuration
description: YAML configuration loader for Angel.
version: 1.0.0
author: thosakwe <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_configuration
dependencies:
  angel_framework: ">=0.0.0-dev < 0.1.0"
  yaml: ">= 2.1.8 < 2.2.0"
dev_dependencies:
  test: ">= 0.12.13 < 0.13.0"