name: angel_validate
description: Cross-platform validation library based on `matcher`.
version: 0.0.2
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/validate
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0-dev
  matcher: ^0.12.0
dev_dependencies:
  angel_diagnostics: ^1.0.0-dev
  angel_test: ^1.0.0-dev
  browser: ^0.10.0
  test: ^0.12.18