author: "Tobe O <thosakwe@gmail.com>"
description: "Shelf interop with Angel."
homepage: "https://github.com/angel-dart/shelf"
name: "angel_shelf"
version: "1.2.0"
dependencies: 
  angel_framework: ">=1.1.0-alpha <2.0.0"
  shelf: "^0.6.0"
dev_dependencies: 
  angel_test: "^1.1.0"
  console: "^2.2.4"
  shelf_proxy: "^0.1.0"
  test: "^0.12.0"
environment: 
  sdk: ">=1.19.0"
