name: angel_static
description: Static server middleware for Angel. Use this to serve files to users.
environment:
  sdk: ">=1.8.0 <3.0.0"
homepage: https://github.com/angel-dart/static
author: Tobe O <thosakwe@gmail.com>
version: 2.0.1
dependencies:
  angel_framework: ^2.0.0-alpha
  file: ^5.0.0
  http_parser: ^3.0.0
  path: ^1.4.2
dev_dependencies:
  angel_test: ^2.0.0-alpha
  http:
  logging: ^0.11.0
  matcher: ^0.12.0
  test: ^1.0.0
