author: "Tobe O <thosakwe@gmail.com>"
description: "Command-line tools for the Angel framework."
homepage: "https://github.com/angel-dart/angel_cli"
name: "angel_cli"
version: 1.1.3
dependencies: 
  # analyzer: "^0.29.0"
  args: ^0.13.4
  code_builder: ^1.0.0
  console: "^2.2.3"
  glob: "^1.1.0"
  http: ^0.11.3
  id: "^1.0.0"
  inflection: "^0.4.1"
  pubspec: "^0.0.14"
  random_string: "^0.0.1"
  recase: "^1.0.0"
  watcher: "^0.9.7"
  yaml: "^2.0.0"
dev_dependencies:
  build_runner: ^0.3.0
  check_for_update: ^1.0.0
environment: 
  sdk: ">=1.19.0"
executables: 
  angel: "angel"
