name: "angel_eventsource"
dependencies: 
  angel_client: "^1.0.0"
  angel_framework: "^1.0.0-dev"
  angel_model: "^1.0.0"
  angel_serialize: "^1.0.0-alpha"
  angel_websocket: "^1.0.0"
  eventsource: "^0.1.0"
  json_god: ^2.0.0-beta
dev_dependencies: 
  angel_serialize_generator: "^1.0.0-alpha"
  build_runner: "^0.5.0"
  console: "^2.2.4"
  test: "^0.12.0"
