name: angel_cache
version: 2.0.0
homepage: https://github.com/angel-dart/cache
description: Support for server-side caching in Angel.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  meta: ^1.0.0
  pool: ^1.0.0
dev_dependencies:
  angel_test: ^2.0.0-alpha
  glob: ^1.0.0
  test: ^1.0.0