name: angel_validate
description: Cross-platform validation library based on `matcher`.
version: 1.0.5-beta
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/validate
environment:
  sdk: ">=1.19.0 <3.0.0"
dependencies:
  angel_framework: ^1.0.0-dev
  angel_http_exception: ^1.0.0
  matcher: ^0.12.0
dev_dependencies:
  angel_test: ^1.0.0-dev
  browser: ^0.10.0
  dart2_constant: ^1.0.0
  logging: ^0.11.0
  test: ^0.12.18