name: angel_sembast
description: package:sembast-powered CRUD services for the Angel framework.
version: 1.0.0
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  sembast: ^1.9.5
dev_dependencies:
  test: ^1.0.0

