name: angel_sync
version: 1.0.0
description: Easily synchronize and scale WebSockets using package:pub_sub.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/sync
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
  angel_websocket: ^1.0.0
  pub_sub: ^1.0.0
dev_dependencies:
  angel_test: ^1.0.0
  test: ^0.12.0