name: angel_seo
description: Helpers for building SEO-friendly Web pages in Angel.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/seo
version: 1.0.0
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  angel_framework: ^1.0.0-dev
  angel_static: ^1.3.0
  dart2_constant: ^1.0.0
  file: ^2.0.0
  html: ^0.13.0
  path: ^1.0.0
dev_dependencies:
  angel_test: ^1.0.0
  test: ^0.12.0