name: angel_framework
version: 1.1.0
description: A high-powered HTTP server with DI, routing and more.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_framework
environment:
  sdk: ">=1.19.0 <2.0.0"
dependencies:
  angel_http_exception: ^1.0.0
  angel_model: ^1.0.0
  angel_route: ^2.0.0
  body_parser: ^1.0.0-dev
  charcode: ^1.0.0
  container: ^0.1.2
  json_god: ^2.0.0-beta
  logging: ">=0.11.3 <1.0.0"
  matcher: ^0.12.0
  merge_map: ^1.0.0
  meta: ^1.0.0
  mime: ^0.9.3
  pool: ^1.0.0
  random_string: ^0.0.1
  tuple: ^1.0.0
dev_dependencies:
  mock_request: ^1.0.0
  http: ^0.11.3
  test: ^0.12.13
