author: "Tobe O <thosakwe@gmail.com>"
description: "angel_auth strategy for in-house OAuth2 login."
homepage: "https://github.com/thosakwe/oauth2_server.git"
name: "angel_auth_oauth2_server"
version: "0.0.0"
dependencies: 
  angel_auth: "^1.0.0-dev"
  angel_framework: "^1.0.0-dev"
dev_dependencies: 
  angel_test: "^1.0.0-dev"
  http: "^0.11.3+9"
  oauth2: "^1.0.2"
  test: "^0.12.18+1"
