author: "Tobe O <thosakwe@gmail.com>"
description: "angel_auth strategy for Twitter login."
environment:
  sdk: ">=1.19.0"
homepage: "https://github.com/angel-dart/auth_twitter.git"
name: "angel_auth_twitter"
version: "1.0.0"
dependencies: 
  angel_auth: "^1.0.0-dev"
  random_string: "^0.0.1"
dev_dependencies: 
  angel_diagnostics: "^1.0.0-dev+5"
