name: angel_static
description: Static server middleware for Angel. Also capable of serving Range responses.
environment:
  sdk: ">=1.8.0 <3.0.0"
homepage: https://github.com/angel-dart/static
author: Tobe O <thosakwe@gmail.com>
version: 2.1.2
dependencies:
  angel_framework: ^2.0.0-alpha
  convert: ^2.0.0
  crypto: ^2.0.0
  file: ^5.0.0
  http_parser: ^3.0.0
  path: ^1.4.2
  range_header: ^2.0.0
dev_dependencies:
  angel_test: ^2.0.0-alpha
  http:
  logging: ^0.11.0
  matcher: ^0.12.0
  test: ^1.0.0
