author: Tobe O <thosakwe@gmail.com>
description: Testing utility library for the Angel framework.
homepage: https://github.com/angel-dart/test.git
name: angel_test
version: 1.1.0+1
dependencies: 
  angel_client: ^1.1.0-alpha
  angel_framework: ^1.1.0-alpha
  angel_validate: ^1.0.0
  angel_websocket: ^1.1.0-alpha
  http: ^0.11.0
  matcher: ^0.12.0+2
  mock_request: ^1.0.0
dev_dependencies: 
  test: ^0.12.17+2
environment: 
  sdk: ">=1.8.9 <3.0.0"
