name: angel_markdown
version: 1.0.0+1
description: Markdown view generator for Angel.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/markdown
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
  markdown: ^0.11.4
dev_dependencies:
  angel_test: ^1.0.0
  test: ^0.12.0