author: "Tobe O <thosakwe@gmail.com>"
description: "angel_auth strategy for Twitter login."
environment:
  sdk: ">=2.0.0 <3.0.0"
homepage: "https://github.com/angel-dart/auth_twitter.git"
name: "angel_auth_twitter"
version: 2.0.0
dependencies: 
  angel_auth: ^2.0.0
  http: ^0.12.0
  random_string: ^0.0.2
  twitter: ^1.0.0
dev_dependencies: 
  logging: ^0.11.0
  pedantic: ^1.0.0
