name: angel_mustache
description: Mustache view generator for Angel.
author: thosakwe <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_mustache
version: 1.1.0
dependencies:
  angel_framework: "^1.1.0-alpha"
  file: ^2.0.0
  mustache4dart: ">= 1.0.0 < 2.0.0"
dev_dependencies:
  http: ">= 0.11.3 < 0.12.0"
  test: ">= 0.12.13 < 0.13.0"
