name: angel_cli
version: 1.0.0-dev
description: Command-line tools for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_cli
executables:
  angel: angel
dependencies:
  args: ">=0.3.4 <1.0.0"
  colorize: ">=0.1.2 <1.0.0"
  console: ">=2.2.3 <3.0.0"
  mustache4dart: ">=1.0.0 <3.0.0"
  yaml: ">=2.0.0 <3.0.0"