name: angel_shelf
description: Shelf interop with Angel. Will be deprecated by v2.0.0.
version: 1.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/shelf
environment:
    sdk: ">=1.19.0"
dependencies:
    angel_framework: ^1.0.0-dev
    shelf: ^0.6.0
dev_dependencies:
    angel_test: ^1.0.0-dev
    test: ^0.12.0