name: angel_cli
version: 1.0.0-dev+2
description: Command-line tools for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_cli
executables:
  angel: angel
dependencies:
  analyzer: ">=0.28.1 <1.0.0"
  args: ">=0.3.4 <1.0.0"
  console: ">=2.2.3 <3.0.0"
  # dart_style: "0.2.9+1 <0.3.0"
  mustache4dart: ">=1.0.0 <3.0.0"
  yaml: ">=2.0.0 <3.0.0"