name: angel_security
version: 0.0.0-alpha+4
description: Angel middleware designed to enhance application security by patching common Web security holes.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/security
dependencies:
    angel_framework: ^1.0.0-dev
dev_dependencies:
    angel_auth: ^1.0.0-dev
    angel_diagnostics: ^1.0.0-dev
    angel_validate: ^1.0.0-beta
    angel_test: ^1.0.0-dev
    test: ^0.12.0