name: angel_wings
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  build_native: ^0.0.11
  mock_request: ^1.0.0
dev_dependencies:
  angel_static: ^2.0.0
  build_runner: ^1.0.0