name: angel_cache
version: 1.0.0
homepage: https://github.com/angel-dart/cache
description: Support for server-side caching in Angel.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0 <3.0.0"
dependencies:
  angel_framework: ">=1.0.0-dev <2.0.0"
  intl: ^0.15.0
  meta: ^1.0.0
  pool: ^1.0.0
dev_dependencies:
  angel_test: ^1.1.0
  glob: ^1.0.0
  test: ^0.12.0