name: angel_rethink
version: 1.0.0
description: RethinkDB-enabled services for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/rethink
dependencies:
  angel_framework: ^1.0.0-dev
  rethinkdb_driver: ^2.3.1
dev_dependencies:
  angel_test: ^1.0.0-dev
  test: ^0.12.0