name: angel_websocket
description: WebSocket plugin for Angel
version: 1.0.0-dev+4
author: thosakwe <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_websocket
dependencies:
  angel_client: ">=1.0.0-dev <2.0.0"
  angel_framework: ">=1.0.0-dev < 2.0.0"
  json_god: ">=2.0.0-beta <3.0.0"
  jwt: ">=0.1.4 <1.0.0"
  uuid: ">=0.5.3 <1.0.0"
dev_dependencies:
  http: ">= 0.11.3 < 0.12.0"
  test: ">= 0.12.13 < 0.13.0"
