name: angel_client
version: 2.0.0-alpha.1
description: Client library for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_client
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_http_exception: ^1.0.0
  collection: ^1.0.0
  http: ^0.11.3
  json_god: ">=2.0.0-beta <3.0.0"
  merge_map: ^1.0.0
dev_dependencies:
  angel_framework: ^2.0.0-alpha
  angel_model: ^1.0.0
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  mock_request: ^1.0.0
  test: ^1.0.0
