name: angel_cli
version: 1.0.0-dev+11
description: Command-line tools for the Angel framework.
environment:
  sdk: ">=1.19.0"
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_cli
executables:
  angel: angel
dependencies:
  args: ^0.13.7
  id: ^1.0.0
  console: ^2.2.3
  yaml: ^2.0.0