name: angel_static
description: Static server middleware for Angel.
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/static
author: Tobe O <thosakwe@gmail.com>
version: 1.2.1
dependencies:
  angel_framework: ^1.0.0-dev
  cli_util: ^0.1.1
  crypto: ^2.0.0
  intl: ">=0.0.0 <1.0.0"
  mime: ^0.9.3
  path: ^1.4.2
  pool: ^1.0.0
  watcher: ^0.9.7
dev_dependencies:
  angel_diagnostics: ^1.0.0
  angel_test: ^1.0.0
  http: ^0.11.3
  test: ^0.12.13
