name: angel_static
description: Static server middleware for Angel.
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/angel_static
author: thosakwe <thosakwe@gmail.com>
version: 1.1.0-dev+2
dependencies:
  angel_framework: ^1.0.0-dev
dev_dependencies:
  http: ^0.11.3
  test: ^0.12.13
