name: angel_configuration
description: Automatic YAML configuration loader for Angel.
version: 2.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_configuration
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  dotenv: ^1.0.0
  file: ^5.0.0
  merge_map: ^1.0.0
  yaml: ^2.0.0
dev_dependencies:
  test: ^1.0.0
