name: angel_mongo
version: 1.0.0-dev
description: Core libraries for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_framework
dependencies:
  angel_framework: ">=0.0.0-dev.17 < 0.1.0"
  json_god: ">=1.0.0 <2.0.0"
  mongo_dart: ">= 0.2.5+1 < 1.0.0"
dev_dependencies:
  http: ">= 0.11.3 < 0.12.0"
  test: ">= 0.12.13 < 0.13.0"