name: angel_configuration
description: Automatic YAML configuration loader for Angel.
version: 2.0.0-rc.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_configuration
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  angel_framework: ^1.1.0-alpha
  dotenv:
    git: https://github.com/thosakwe/dotenv.git
  file: ^2.0.0
  merge_map: ^1.0.0
  yaml: ^2.0.0
dev_dependencies:
  test: ^0.12.0
