name: body_parser
author: Tobe O <thosakwe@gmail.com>
version: 1.0.0-dev
description: Parse request bodies and query strings in Dart.
homepage: https://github.com/thosakwe/body_parser
dev_dependencies:
  http: any
  json_god: any
  test: any