name: angel_route
description: A powerful, isomorphic routing library for Dart.
version: 2.0.6
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_route
environment:
  sdk: ">=1.19.0 <3.0.0"
dependencies:
  combinator: ^1.0.0
  meta: ^1.0.0
  path: ^1.0.0
  string_scanner: ^1.0.0
dev_dependencies:
  browser: ">=0.10.0 < 0.11.0"
  dart2_constant: ^1.0.0
  http: ">=0.11.3 <0.12.0"
  test: ">=0.12.15 <0.13.0"