name: angel_serialize
version: 0.0.0
description: Model serialization generators.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/serialize
dependencies:
  code_builder: ^1.0.0
  id: ^1.0.0
  recase: ^1.0.0
  source_gen: ^0.5.8
dev_dependencies:
  angel_framework: ^1.0.0
  build_runner: ^0.3.0
  test: ">= 0.12.13 < 0.13.0"