name: code_buffer
version: 2.0.0
description: An advanced StringBuffer geared toward generating code, and source maps.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/code_buffer
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
  source_span: ^1.8.1
dev_dependencies:
  test: ^1.16.8