name: code_buffer
version: 2.0.0
description: An advanced StringBuffer geared toward generating code, and source maps.
homepage: https://github.com/dukefirehawk/angel
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
  source_span: ^1.8.1
dev_dependencies:
  test: ^1.17.3