name: angel3_orm_test
version: 3.0.0-beta.1
description: Common tests for Angel ORM backends.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/orm/angel_orm_test
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_migration: ^4.0.0-beta.1
  angel3_model: ^3.0.0
  angel3_orm: ^4.0.0-beta.1
  angel3_serialize: ^4.0.0
  test: ^1.17.4
dev_dependencies:
  angel3_orm_generator: ^4.0.0-beta.1
  angel3_framework: ^4.0.0
  build_runner: ^2.0.1
  optional: ^6.0.0-nullsafety.2
