name: angel_orm_test
publish_to: none
description: Common tests for Angel ORM backends.
environment:
  sdk: '>=2.10.0 <2.12.0'
dependencies:
  angel_migration:
    path: ../angel_migration
  angel_model: #^1.0.0
    path: ../../model
  angel_orm: #^2.0.0
    path: ../angel_orm
  angel_serialize: #^2.0.0
    path: ../../serialize/angel_serialize
  test: ^1.15.7
dev_dependencies:
  angel_orm_generator:
    path: ../angel_orm_generator
  angel_framework: #^2.0.0
    path: ../../framework
  build_runner: ^1.0.0
#dependency_overrides:
#  angel_orm:
#    path: ../angel_orm