name: angel3_combinator
version: 2.0.1
description: Packrat parser combinators that support static typing, generics, file spans, memoization, and more.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/combinator
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_code_buffer: ^2.0.0
  matcher: ^0.12.10
  source_span: ^1.8.1
  string_scanner: ^1.1.0
  tuple: ^2.0.0
dev_dependencies:
  test: ^1.17.4