dependencies:
  collection: ^1.15.0-nullsafety.4
name: symbol_table
version: 2.0.0
description: A generic symbol table implementation in Dart, with support for scopes and constants.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/symbol_table
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.15.7