name: symbol_table
version: 2.0.0
description: A generic symbol table implementation in Dart, with support for scopes and constants.
homepage: https://github.com/thosakwe/symbol_table
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0  
dev_dependencies:
  test: ^1.17.3