name: angel3_container
version: 3.1.1
description: Angel3 hierarchical DI container, and pluggable backends for reflection.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/container/angel_container
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  quiver: ^3.0.1
dev_dependencies:
  test: ^1.17.5
  lints: ^1.0.0