name: angel3_container
version: 3.0.1
description: A hierarchical DI container, and pluggable backends for reflection.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/container/angel_container
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  quiver: ^3.0.1
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4