name: angel_container
version: 3.0.0
description: A hierarchical DI container, and pluggable backends for reflection.
homepage: https://github.com/dukefirehawk/angel
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  quiver: ^3.0.0
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8