name: angel_container
version: 1.1.0
author: Tobe O <thosakwe@gmail.com>
description: A hierarchical DI container, and pluggable backends for reflection.
homepage: https://github.com/angel-dart/container.git
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  collection: ^1.14.13
  quiver: ^2.1.5
dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7