name: angel3_html
version: 3.0.0
description: Support for rendering html_builder AST's as responses in Angel.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/html_builder
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.0.0
  belatuk_html_builder: ^3.0.0
dev_dependencies:
  angel3_test: ^4.0.0
  html: ^0.15.0
  logging: ^1.0.1
  test: ^1.17.0
  lints: ^1.0.0