name: angel3_oauth2
version: 4.0.0
description: A class containing handlers that can be used within Angel to build a spec-compliant OAuth 2.0 server.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/oauth2
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel3_framework: ^4.0.0
  angel3_http_exception: ^3.0.0
  crypto: ^3.0.1
  collection: ^1.15.0
dev_dependencies: 
  angel3_validate: ^4.0.0
  angel3_test: ^4.0.0
  logging: ^1.0.1
  oauth2: ^2.0.0
  pedantic: ^1.11.0
  test: ^1.17.5
  uuid: ^3.0.4
