name: angel3_json_god
version: 4.0.0
description: Easy JSON serialization and deserialization in Dart.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/json_god
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  #dart2_constant: ^1.0.0
  logging: ^1.0.1
dev_dependencies:
  stack_trace: ^1.10.0
  test: ^1.17.4