name: json_god
version: 4.0.0
authors:
  - Tobe O <thosakwe@gmail.com>
description: Easy JSON serialization and deserialization in Dart.
homepage: https://github.com/thosakwe/json_god
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  #dart2_constant: ^1.0.0
  logging: ^1.0.1
dev_dependencies:
  stack_trace: ^1.10.0
  test: ^1.16.8