name: "angel3_auth_twitter"
version: 3.0.0
description: "package:angel3_auth strategy for Twitter login. Auto-signs requests."
homepage: "https://github.com/angel-dart/auth_twitter.git"
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  angel_auth: ^2.0.0
  angel_framework: ^2.0.0
  http: ^0.13.0
  path: ^1.0.0
  twitter:
    git: 
      url: https://github.com/dukefirehawk/twitter.dart.git
      ref: sdk-2.12.x
dev_dependencies:
  logging: ^1.0.0
  pedantic: ^1.11.0
