name: "angel3_auth_twitter"
description: Angel3 authentication strategy for Twitter login. Auto-signs requests.
version: 3.0.0
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/auth_twitter
publish_to: none
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  angel3_auth: ^6.0.0
  angel3_framework: ^6.0.0
  http: ^0.13.0
  path: ^1.0.0
  oauth1: ^2.0.0
  dart_twitter_api: ^0.5.6+1
dev_dependencies:
  logging: ^1.0.0
  lints: ^2.0.0
