name: angel_container
version: 1.0.0-alpha.6
author: Tobe O <thosakwe@gmail.com>
description: "A better IoC container and dependency injector for Angel, ultimately allowing Angel to be used without dart:mirrors."
homepage: https://github.com/angel-dart/container.git
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  collection: ^1.0.0
  quiver: ^2.0.0
dev_dependencies:
  test: