author: Tobe O <thosakwe@gmail.com>
description: Angel CORS middleware. Port of expressjs/cors to the Angel framework.
environment:
  sdk: ">=2.10.0 <3.0.0"
homepage: https://github.com/angel-dart/cors.git
name: angel_cors
version: 3.0.0
publish_to: none
dependencies: 
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/framework
dev_dependencies:
  angel_test:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/test
  http: ^0.13.0
  pedantic: ^1.11.0
  test: ^1.16.5
