name: angel3_cors
version: 4.1.0
description: Angel3 CORS middleware. Ported from expressjs/cors to Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/cors
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel3_framework: ^4.2.0
dev_dependencies:
  angel3_test: ^4.0.0
  http: ^0.13.3
  lints: ^1.0.0
  test: ^1.17.5
