author: Tobe O <thosakwe@gmail.com>
description: Angel CORS middleware. Port of expressjs/cors to the Angel framework.
environment:
  sdk: ">=2.10.0 <2.12.0"
homepage: https://github.com/angel-dart/cors.git
name: angel_cors
version: 2.0.0
dependencies: 
  angel_framework: #^2.0.0-alpha
    path: ../framework
dev_dependencies:
  angel_test: #^2.0.0
    path: ../test
  http: ^0.12.0
  pedantic: ^1.0.0
  test: ^1.15.7
