name: angel3_cors
version: 4.0.0
description: Angel CORS middleware. Port of expressjs/cors to the Angel framework.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/cors
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel3_framework: ^4.0.0
dev_dependencies:
  angel3_test: ^4.0.0
  http: ^0.13.3
  pedantic: ^1.11.0
  test: ^1.17.5
