name: angel3_markdown
version: 4.1.0
description: Angel3 Markdown view generator. Write static sites, with no build step.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/markdown
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  file: ^6.1.2
  markdown: ^4.0.0
dev_dependencies:
  angel3_test: ^4.0.0
  lints: ^1.0.0
  test: ^1.17.0
