name: angel3_markdown
version: 3.0.0
description: Angel3 Markdown view generator. Write static sites, with no build step.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/markdown
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  angel3_framework: ^4.0.0
  file: ^6.1.2
  markdown: ^4.0.0
dev_dependencies:
  angel3_test: ^4.0.0
  pedantic: ^1.11.0
  test: ^1.17.0
