name: angel3_auth
description: A complete authentication plugin for Angel. Includes support for stateless JWT tokens, Basic Auth, and more.
version: 4.0.0
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/auth
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.0.0
  charcode: ^1.2.0
  collection: ^1.15.0
  crypto: ^3.0.0
  http_parser: ^4.0.0
  meta: ^1.3.0
  quiver: ^3.0.0
dev_dependencies:
  http: ^0.13.1
  io: ^1.0.0
  logging: ^1.0.0
  pedantic: ^1.11.0
  test: ^1.17.4
