name: angel_auth
description: A complete authentication plugin for Angel. Includes support for stateless JWT tokens, Basic Auth, and more.
version: 2.3.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_auth
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  angel_framework: ^2.3.0
  charcode: ^1.0.0
  collection: ^1.0.0
  crypto: ^3.0.0
  http_parser: ^4.0.0
  meta: ^1.0.0
  quiver_hashcode: ^2.0.0
dev_dependencies:
  http: ^0.13.0
  io: ^1.0.0
  logging: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.15.7
dependency_overrides:
  angel_framework:
    path: ../framework
  angel_route:
    path: ../route
  angel_model:
    path: ../model
  angel_http_exception:
    path: ../http_exception
  angel_container: 
    path: ../container/angel_container
