name: angel3_jael2
version: 4.0.0
description: Angel support for the Jael templating engine, similar to Blade or Liquid.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/jael/angel_jael
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.0.0
  angel3_code_buffer: ^2.0.0
  jael2:
  jael2_preprocessor:
  angel3_symbol_table: ^2.0.0
  file: ^6.0.0

dev_dependencies:
  angel3_test: ^4.0.0
  html: ^0.15.0
  test: ^1.17.3
dependency_overrides:
  web_socket_channel: ^2.0.0
  http: ^0.13.0