name: angel3_auth_oauth2
version: 4.0.2
description: Angel3 library for authenticating users with external identity providers via OAuth2.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/auth_oauth2
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.0
  angel3_framework: ^4.0.0
  http_parser: ^4.0.0
  oauth2: ^2.0.0
dev_dependencies:
  logging: ^1.0.1
  pedantic: ^1.11.0