name: angel3_auth_oauth2
version: 4.0.0
description: angel_auth strategy for OAuth2 login, i.e. Facebook, Github, etc.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/auth_oauth2
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.0
  angel3_framework: ^4.0.0
  http_parser: ^4.0.0
  oauth2: ^2.0.0
dev_dependencies:
  logging: ^1.0.1
  pedantic: ^1.11.0