name: angel_container_generator
version: 2.0.0
author: Tobe O <thosakwe@gmail.com>
description: Codegen support for using pkg:reflectable with pkg:angel_container.
homepage: https://github.com/angel-dart/container.git
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  angel_container:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/container/angel_container
  reflectable: ^2.2.9
dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  test: ^1.16.5