name: angel_container_generator
version: 1.0.1
author: Tobe O <thosakwe@gmail.com>
description: Codegen support for using pkg:reflectable with pkg:angel_container.
homepage: https://github.com/angel-dart/container.git
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  angel_container: # ^1.0.0-alpha
    path: ../angel_container
  reflectable: ^2.2.9
dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  test: ^1.15.7