name: angel3_paginate
version: 6.0.0
description: Platform-agnostic pagination library, with custom support for the Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/paginate
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_framework: ^6.0.0
dev_dependencies:
  angel3_test: ^6.0.0
  logging: ^1.0.1
  test: ^1.21.0
  lints: ^1.0.0