name: angel3_http_exception
version: 3.0.2
description: Exception class that can be serialized to JSON and serialized to clients.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/http_exception
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.11.0