name: angel_eventsource
version: 2.0.0
description: Server-sent Events (SSE) plugin for Angel.
homepage: https://github.com/angel-dart/eventsource
author: Tobe O <thosakwe@gmail.com>
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/framework
  angel_websocket:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/websocket
  eventsource:
    git: 
      url: https://github.com/dukefirehawk/dart-eventsource.git
  stream_channel: ^2.0.0
dev_dependencies: 
  console: ^4.0.0
  logging: ^1.0.0
  test: ^1.16.5
