targets:
  _json_model_builder:
  _serializer_builder:

builders:
  json_model:
    target: "_json_model_builder"
    import: "package:angel_serialize_generator/angel_serialize_generator.dart"
    builder_factories:
      - jsonModel
    auto_apply: dependents
    build_extensions:
      .dart:
        - ".g.dart"
  serializer:
    target: "_serializer_builder"
    import: "package:angel_serialize_generator/angel_serialize_generator.dart"
    builder_factories:
      - serializeGenerator
    auto_apply: dependents
    build_extensions:
      .dart:
        - ".serializer.g.dart"