builders:
  angel_serialize:
    target: "angel_serialize_generator"
    import: "package:angel_serialize_generator/angel_serialize_generator.dart"
    builder_factories:
      - jsonModelBuilder
      - serializerBuilder
      - typescriptDefinitionBuilder
    auto_apply: root_package
    build_to: source
    build_extensions:
      .dart:
        - ".g.dart"
        - ".serializer.g.dart"
        - ".d.ts"
    required_inputs:
      - .dart
targets:
  _book:
    sources:
      - "test/models/book.dart"
      - "test/models/game_pad_button.dart"
      - "test/models/with_enum.dart"
  _typescript_definition:
    sources:
        - "test/*.dart"
  $default:
    dependencies:
      - ":_book"
    sources:
      - "test/models/author.dart"
      - "test/models/game_pad.dart"
