name: angel_serialize_generator
version: 2.0.0-alpha
description: Model serialization generators, designed for use with Angel.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/serialize
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_serialize:
    path: ../angel_serialize
  code_builder: ^2.0.0
  id: ^1.0.0
  recase: ^1.0.0
  source_gen: ^0.7.0
dev_dependencies:
  angel_framework: ^1.0.0
  build_runner: ^0.6.0
  test: ">= 0.12.13 < 0.13.0"