name: angel_serialize_generator
version: 2.0.2
description: Model serialization generators, designed for use with Angel. Combine with angel_serialize for flexible modeling.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/serialize
environment:
  sdk: '>=2.0.0-dev.1.2 <2.0.0'
dependencies:
  angel_serialize: ^2.0.0-alpha
  build_config: ">=0.2.4 <2.0.0"
  code_builder: ^3.0.0
  id: ^1.0.0
  recase: ^1.0.0
  source_gen: ^0.7.0
dev_dependencies:
  angel_framework: ^1.0.0
  build_runner: ^0.7.0
  test: ">= 0.12.13 < 0.13.0"