name: angel_serialize_generator
version: 2.0.8+3
description: Model serialization generators, designed for use with Angel. Combine with angel_serialize for flexible modeling.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/serialize
environment:
  sdk: '>=2.0.0-dev.1.2 <3.0.0'
dependencies:
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0-alpha
  build_config: ">=0.2.4 <2.0.0"
  code_buffer: ^1.0.0
  code_builder: ^3.0.0
  id: ^1.0.0
  meta: ^1.0.0
  recase: ^1.0.0
  source_gen: ^0.7.0
dev_dependencies:
  build_runner: ^0.8.0
  test: ^1.0.0