name: angel_orm
version: 1.0.0-alpha+11
description: Runtime support for Angel's ORM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
environment:
  sdk: '>=2.0.0-dev.1.2 <2.0.0'
dependencies:
  angel_model: ^1.0.0
  meta: ^1.0.0