name: angel_orm
version: 2.0.0-dev.3
description: Runtime support for Angel's ORM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
environment:
  sdk: '>=2.0.0-dev.1.2 <3.0.0'
dependencies:
  intl: ^0.15.7
  meta: ^1.0.0
  string_scanner: ^1.0.0
dev_dependencies:
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0