name: angel_orm
version: 1.0.0-alpha+1
description: Runtime support for Angel's ORM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
environment:
  sdk: ">=1.19.0"
dependencies:
  intl: ^0.15.1
  pool: ^1.0.0
  postgres: ^0.9.5