name: angel_container_generator
version: 1.0.0-alpha
author: Tobe O <thosakwe@gmail.com>
description: Code generator that generates `Reflector` subclasses. Use this to run Angel applications on Flutter, where reflection via `dart:mirrors` is disallowed.
homepage: https://github.com/angel-dart/container.git
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_container: ^1.0.0-alpha
  build: ^0.12.0
  build_config: ^0.3.0
  source_gen: ^0.9.0
dev_dependencies:
  build_runner: ^0.10.0