name: angel_orm_mysql
version: 1.0.0-dev
description: MySQL support for Angel's ORM. Includes functionality for querying and transactions.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
environment:
  sdk: '>=2.0.0-dev.1.2 <3.0.0'
dependencies:
  angel_orm: ^2.0.0-dev
  logging: ^0.11.0
  pool: ^1.0.0
  sqljocky5: ^2.0.0
dev_dependencies:
  test: ^1.0.0