name: angel3_static
version: 6.0.0
description: This library provides a virtual directory to serve static files for Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/static
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  angel3_framework: ^4.1.0
  belatuk_range_header: ^4.0.0
  convert: ^3.0.0
  crypto: ^3.0.1
  file: ^6.1.0
  http_parser: ^4.0.0
  path: ^1.8.0
  logging: ^1.0.1
dev_dependencies:
  angel3_test: ^4.0.0
  http: ^0.13.2
  matcher: ^0.12.10
  lints: ^1.0.0
  test: ^1.17.4
  
