name: angel_migration_runner
version: 2.0.0
description: Command-line based database migration runner for Angel's ORM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/migration
environment:
  sdk: '>=2.10.0 <2.12.0'
dependencies:
  angel_migration: #^2.0.0-alpha
    path: ../angel_migration
  angel_orm: #^2.0.0-dev.2
    path: ../angel_orm
  args: ^1.0.0
  charcode: ^1.0.0
  postgres: ^2.2.0