name: angel3_migration_runner
version: 4.0.0-beta.3
description: Command-line based database migration runner for Angel3's ORM.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/orm/angel_migration_runner
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_migration: ^4.0.0-beta.1
  angel3_orm: ^4.0.0-beta.1
  args: ^2.1.0
  charcode: ^1.2.0
  postgres: ^2.3.2
dev_dependencies:
  pedantic: ^1.11.0
