name: angel3_migration_runner
version: 6.1.0
description: Command-line based database migration runner for Angel3's ORM.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_migration_runner
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_migration: ^6.0.0
  angel3_orm: ^6.0.0
  args: ^2.1.0
  charcode: ^1.2.0
  postgres: ^2.4.0
  mysql_client: ^0.0.24
  mysql1: ^0.20.0
  logging: ^1.0.0
dev_dependencies:
  lints: ^2.0.0
# dependency_overrides:
#    angel3_orm:
#      path: ../angel_orm
#    angel3_migration:
#      path: ../angel_migration
