name: angel3_model
version: 3.0.2
description: Angel3 basic data model class, no longer with the added weight of the whole framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/model
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.11.0
