name: angel3_serialize
version: 6.0.0
description: Static annotations powering Angel3 model serialization. Combine with angel3_serialize_generator for flexible modeling.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/serialize/angel_serialize
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_model: ^6.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  quiver: ^3.0.1
dev_dependencies:
  lints: ^1.0.0
# dependency_overrides:
#   angel3_model:
#     path: ../../model
  
