name: angel3_serialize
version: 4.0.0
description: Static annotations powering Angel model serialization. Combine with angel_serialize_generator for flexible modeling.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/serialize/angel_serialize
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_model: ^3.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  pedantic: ^1.11.0
  quiver: ^3.0.1
