name: angel3_production
version: 3.0.1
description: Helpers for concurrency, message-passing, rotating loggers, and other production functionality in Angel.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/production
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_container: ^3.0.0
  angel3_framework: ^4.0.0
  angel3_pub_sub: ^3.0.0
  args: ^2.1.0
  io: ^1.0.0
  logging: ^1.0.1
dev_dependencies:
  pedantic: ^1.11.0