name: angel3_production
version: 3.1.2
description: Helpers for concurrency, message-passing, rotating loggers, and other production functionality in Angel3.
homepage: https://angel3-framework.web.app
repository: https://github.com/dukefirehawk/angel/tree/master/packages/production
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_container: ^3.1.0
  angel3_framework: ^4.2.0
  belatuk_pub_sub: ^4.0.0
  args: ^2.3.0
  io: ^1.0.0
  logging: ^1.0.1
dev_dependencies:
  lints: ^1.0.1
