name: angel3_orm_postgres
version: 3.0.0-beta.1
description: PostgreSQL support for Angel's ORM. Includes functionality for querying and transactions.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/orm/angel_orm_postgres
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_orm: ^4.0.0-beta.1
  logging: ^1.0.1
  pool: ^1.5.0
  postgres: ^2.3.2
  #optional: ^6.0.0-nullsafety.2

dev_dependencies:
  angel3_pretty_logging: ^3.0.0
  test: ^1.17.4
  pedantic: ^1.11.0
  #angel3_orm_test:
  #   path: ../angel_orm_test
