name: angel_orm_postgres
version: 2.0.0
description: PostgreSQL support for Angel's ORM. Includes functionality for querying and transactions.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  angel_orm:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/orm/angel_orm
  logging: ^1.0.0
  pool: ^1.0.0
  postgres:
    git: 
      url: https://github.com/dukefirehawk/postgresql-dart

dev_dependencies:
  angel_orm_test:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/orm/angel_orm_test
  pretty_logging:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/pretty_logging
  test: ^1.15.7
