name: build_jael
version: 1.0.0
description: Compile Jael files to HTML using the power of `package:build`.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/jael/tree/master/build_jael
environment:
  sdk: ">=1.19.0 <=2.0.0"
dependencies:
  build: ^0.12.0
  build_config: ^0.2.0
  code_buffer: ^1.0.0
  file: ^2.0.0
  jael: ^1.0.0-alpha
  jael_preprocessor: ^1.0.0-alpha
  symbol_table: ^1.0.0
dev_dependencies:
  build_runner: ^0.7.0