name: jael_preprocessor
version: 1.0.0-alpha+2
description: A pre-processor for resolving blocks and includes within Jael templates.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/jael/tree/master/jael_processor
environment:
  sdk: ">=1.19.0"
dependencies:
  file: ^2.0.0
  jael: ^1.0.0-alpha
dev_dependencies:
  test: ^0.12.0