name: jael3_web
version: 1.0.0
description: Experimental virtual DOM/SPA engine built on Jael. Supports SSR.
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  build: ^2.0.2
  build_config: ^1.0.0
  code_builder: ^4.0.0
  jael3: ^4.2.0
  jael3_preprocessor: ^4.2.0
  source_gen: ^1.0.2
dev_dependencies:
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0
  lints: ^1.0.0