name: angel3_orm_mysql
version: 2.0.0-beta.1
description: MySQL support for Angel3's ORM. Includes functionality for querying and transactions.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/orm/angel_orm_mysql
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_orm: ^4.0.0-beta.1
  logging: ^1.0.0
  pool: ^1.5.0
  galileo_sqljocky5: ^3.0.0
  #optional: ^6.0.0-nullsafety.2
dev_dependencies:
  angel3_migration: ^4.0.0-beta.1
  angel3_orm_generator: ^4.0.0-beta.1
  build_runner: ^2.0.0
  test: ^1.17.0
  pedantic: ^1.11.0
  angel3_orm_test:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: angel3
      path: packages/orm/angel_orm_test
