name: angel3_orm_mysql
version: 6.0.0-beta.1
description: MySQL support for Angel3 ORM. Includes functionality for querying and transactions.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_orm_mysql
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  angel3_orm: ^6.0.0
  logging: ^1.0.0
  mysql1: ^0.19.0
  optional: ^6.0.0
dev_dependencies:
  angel3_orm_test: ^6.0.0
  test: ^1.17.0
  lints: ^1.0.0
dependency_overrides:
  angel3_serialize:
    path: ../../serialize/angel_serialize
  angel3_model:
    path: ../../model
  angel3_orm_test:
    path: ../angel_orm_test
  angel3_orm:
    path: ../angel_orm
  angel3_migration:
    path: ../angel_migration


