name: angel3_websocket
description: This library provides WebSockets support for Angel3 framework.
version: 4.0.2
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/websocket
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.0
  angel3_client: ^4.0.0
  angel3_framework: ^4.0.0
  angel3_http_exception: ^3.0.0
  angel3_merge_map: ^2.0.0
  http: ^0.13.1
  meta: ^1.3.0
  stream_channel: ^2.1.0
  web_socket_channel: ^2.1.0
  collection: ^1.15.0
  logging: ^1.0.1
dev_dependencies:
  angel3_container: ^3.0.0
  angel3_model: ^3.0.0
  pedantic: ^1.11.0
  test: ^1.17.4


  