name: angel_websocket
description: Support for using pkg:angel_client with WebSockets. Designed for Angel.
environment:
  sdk: ">=2.10.0 <3.0.0"
version: 3.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_websocket
publish_to: none
dependencies:
  angel_auth: ^3.0.0
  angel_client: ^3.0.0
  angel_framework: ^3.0.0
  angel_http_exception: ^2.0.0
  http: ">=0.11.0 <0.13.0"
  merge_map: ^1.0.0
  meta: ^1.0.0
  stream_channel: ^2.0.0
  web_socket_channel: ^1.0.0
dev_dependencies:
  angel_container: ^2.0.0
  angel_model: ^2.0.0
#  logging: ^0.11.0
  pedantic: ^1.0.0
  test: ^1.15.7
dependency_overrides:
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/framework
  angel_http_exception:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/http_exception
  angel_container: 
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/container/angel_container
  angel_model:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/model
  angel_route:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/route
  angel_auth:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/auth
  angel_client:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/angel_client
  