name: angel3_mock_request
version: 6.0.0
description: Manufacture dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/mock_request
environment:
    sdk: '>=2.15.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
dev_dependencies:
  angel3_framework: ^4.2.0
  http: ^0.13.2
  test: ^1.17.4
  lints: ^1.0.0
dependency_overrides:
  angel3_framework:
    path: ../framework
