name: mock_request
version: 2.0.0
description: Manufacture dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/mock_request
environment:
    sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
dev_dependencies:
  #angel_framework: ^2.1.0
  http: ^0.13.0
  test: ^1.16.8
