name: angel3_mock_request
version: 2.0.0
description: Manufacture dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/mock_request
environment:
    sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
dev_dependencies:
  #angel_framework: ^2.1.0
  http: ^0.13.2
  test: ^1.17.4
