name: pub_sub
version: 3.0.0
description: Keep application instances in sync with a simple pub/sub API.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/pub_sub
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  json_rpc_2: ^3.0.0
  stream_channel: ^2.1.0
  uuid: ^3.0.4
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
