name: angel3_configuration
version: 4.1.0
description: Automatic YAML application configuration loader for Angel 3, with .env support.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/configuration
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  belatuk_merge_map: ^3.0.0
  dotenv: ^3.0.0
  file: ^6.1.0
  yaml: ^3.1.0
dev_dependencies:
  io: ^1.0.0
  logging: ^1.0.1
  lints: ^1.0.0
  belatuk_pretty_logging: ^4.0.0
  test: ^1.17.5
#dependency_overrides:
#  angel3_framework:
#    path: ../framework