name: angel3_configuration
description: Automatic YAML application configuration loader for Angel, with .env support.
version: 4.0.0
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/configuration
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.0.0
  angel3_merge_map: ^2.0.0
  dotenv: ^3.0.0
  file: ^6.1.0
  yaml: ^3.1.0
dev_dependencies:
  io: ^1.0.0
  logging: ^1.0.1
  pedantic: ^1.11.0
  angel3_pretty_logging: ^3.0.0
  test: ^1.17.3
