name: angel3_proxy
version: 4.1.0
description: Angel middleware to forward requests to another server (i.e. pub serve).
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/proxy
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  http: ^0.13.3
  http_parser: ^4.0.0
  path: ^1.8.0
dev_dependencies:
  angel3_test: ^4.0.0
  angel3_mock_request: ^2.0.0
  logging: ^1.0.1
  lints: ^1.0.0
  test: ^1.17.7
  
