builders:
  angel_orm:
    import: "package:angel_orm_generator/angel_orm_generator.dart"
    builder_factories:
      - migrationBuilder
      - ormBuilder
    auto_apply: root_package
    build_to: cache
    build_extensions:
      .dart:
        - ".angel_migration.g.part"
        - ".angel_orm.g.part"
    required_inputs:
      - angel_serialize.g.part
      - angel_serialize_serializer.g.part
    applies_builders:
      - angel_serialize_generator|angel_serialize
      - source_gen|combining_builder
      - source_gen|part_cleanup"
    
targets:
  _standalone:
    sources:
      - lib/src/models/author.dart
      - lib/src/models/car.dart
      - lib/src/models/customer.dart
      - lib/src/models/foot.dart
      - lib/src/models/fruit.dart
      - lib/src/models/has_map.dart
      - lib/src/models/role.dart
      - lib/src/models/unorthodox.dart
  $default:
    dependencies:
      - angel_serialize_generator
      - :_standalone
    sources:
      - lib/src/models/book.dart
      - lib/src/models/has_car.dart
      - lib/src/models/leg.dart
      - lib/src/models/order.dart
      - lib/src/models/tree.dart
      - lib/src/models/user.dart