name: angel_orm_test
publish_to: none
dependencies:
  angel_migration: ^2.0.0-alpha
  angel_model: ^1.0.0
  test: ^1.0.0
dev_dependencies:
  angel_orm_generator:
    path: ../angel_orm_generator
  build_runner: ^1.0.0