name: angel_orm_generator
version: 4.0.0
description: Code generators for Angel's ORM. Generates query builder classes.
homepage: https://github.com/dukefirehawk/angel
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  analyzer: ">=0.35.0 <2.0.0"
  angel_model:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/model
  angel_serialize:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/serialize/angel_serialize
  angel_orm:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/orm/angel_orm
  angel_serialize_generator:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/serialize/angel_serialize_generator
  build: ^1.0.0
  build_config: ^0.4.0
  code_builder: ^3.0.0
  dart_style: ^1.0.0
  inflection2: ^0.4.2
  meta: ^1.0.0
  path: ^1.0.0
  recase: ^3.0.1
  source_gen: ^0.9.0
dev_dependencies:
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/framework
  angel_migration:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/orm/angel_migration
  #angel_test: ^1.0.0
  build_runner: ^1.11.5
  collection: ^1.0.0
  pedantic: ^1.11.0
  postgres: ^2.2.0
  #  git: 
  #    url: https://github.com/dukefirehawk/postgresql-dart
  test: ^1.16.5
