name: angel3_orm
version: 4.0.0-beta.1
description: Runtime support for Angel's ORM. Includes base classes for queries.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/orm/angel_orm
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
  intl: ^0.17.0
  meta: ^1.3.0
  string_scanner: ^1.1.0
  optional: ^6.0.0-nullsafety.2
dev_dependencies:
  angel3_model: ^3.0.0
  angel3_serialize: ^4.0.0
  angel3_serialize_generator: ^4.0.0
  build_runner: ^2.0.1
  pedantic: ^1.11.0
  test: ^1.17.4
