name: angel3_orm
version: 6.1.0
description: Runtime support for Angel3 ORM. Includes base classes for queries.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_orm
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
  intl: ^0.17.0
  meta: ^1.3.0
  string_scanner: ^1.1.0
  optional: ^6.0.0
  logging: ^1.0.0
dev_dependencies:
  angel3_model: ^6.0.0
  angel3_serialize: ^6.0.0
  angel3_serialize_generator: ^6.0.0
  build_runner: ^2.1.1
  test: ^1.17.4
  lints: ^2.0.0
# dependency_overrides:
#   angel3_serialize:
#     path: ../../serialize/angel_serialize
#   angel3_serialize_generator:
#     path: ../../serialize/angel_serialize_generator
#   angel3_model:
#     path: ../../model