name: angel3_sembast
version: 2.0.1
description: A plugin service that persist data to Sembast for Angel3 framework.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/sembast
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.0.0
  sembast: ^3.1.0+2
dev_dependencies:
  angel3_http_exception: ^3.0.0
  logging: ^1.0.1
  pedantic: ^1.11.1
  test: ^1.17.8

