name: angel3_sembast
version: 3.0.1
description: A plugin service that persist data to Sembast for Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/sembast
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  sembast: ^3.1.1
dev_dependencies:
  angel3_http_exception: ^3.1.0
  logging: ^1.0.1
  lints: ^1.0.0
  test: ^1.17.8

