name: angel3_seo
version: 6.0.0
description: Helper infrastructure for building SEO-friendly Web backends in Angel3.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/seo
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_framework: ^6.0.0
  angel3_static: ^6.0.0
  file: ^6.1.2
  html: ^0.15.0
  http_parser: ^4.0.0
  path: ^1.8.0
dev_dependencies:
  angel3_test: ^6.0.0
  logging: ^1.0.1
  test: ^1.17.8
  lints: ^1.0.0