name: angel3_redis
version: 6.0.0
description: An Angel3 service provider for Redis. Works well for caching volatile data.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/redis
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_framework: ^6.0.0
  angel3_http_exception: ^6.0.0
  resp_client: ^1.2.0
dev_dependencies:
  test: ^1.17.8
  lints: ^1.0.0
