name: angel3_file_service
version: 4.1.0
description: Angel service that persists data to a file on disk, stored as a JSON list.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/file_service
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  file: ^6.1.1
  pool: ^1.5.0
dev_dependencies:
  test: ^1.17.7
  lints: ^1.0.0
