name: angel3_validate
description: Cross-platform request body validation library based on `matcher`.
version: 4.1.0
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/validate
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.2.0
  angel3_http_exception: ^3.0.0
  matcher: ^0.12.0
dev_dependencies:
  #angel3_test:
  angel3_mock_request: ^2.0.0
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
  logging: ^1.0.1
  lints: ^1.0.0
  test: ^1.17.4