name: angel_validate
description: Cross-platform request body validation library based on `matcher`.
version: 2.0.2
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/validate
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  angel_framework: #^2.0.0-alpha
    path: ../framework
  angel_http_exception: #^1.0.0
    path: ../http_exception
  matcher: ^0.12.0
dev_dependencies:
  angel_test: #^2.0.0-alpha
    path: ../test
  build_runner: ^1.11.1
  build_web_compilers: ^2.12.2
  logging: ^0.11.0
  mock_request:
  pedantic: ^1.0.0
  test: ^1.15.7