name: angel3_validate
description: Cross-platform request body validation library based on `matcher`.
version: 4.0.0
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/validate
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.0.0
  angel3_http_exception: ^3.0.0
  matcher: ^0.12.0
dev_dependencies:
  #angel3_test:
  build_runner: ^1.11.1
  build_web_compilers: ^2.12.2
  logging: ^1.0.1
  angel3_mock_request: ^2.0.0
  pedantic: ^1.0.0
  test: ^1.17.4