name: jael_preprocessor
version: 3.0.0
description: A pre-processor for resolving blocks and includes within Jael templates.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/jael/tree/master/jael_preprocessor
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  file: ^6.1.0
  jael:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/jael/jael
  symbol_table: ^2.0.0
dev_dependencies:
  code_buffer:
  test: ^1.15.7