name: jael_preprocessor
version: 4.0.0
description: A pre-processor for resolving blocks and includes within Jael templates.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/jael/tree/master/jael_preprocessor
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  file: ^6.1.0
  jael:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/jael/jael
  symbol_table:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/symbol_table
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  code_buffer:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/code_buffer

  test: ^1.17.3