name: angel3_shelf
version: 3.0.0-dev.1
description: Shelf interop with Angel3. Use this to wrap existing server code.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/shelf
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.1.0
  path: ^1.8.0
  shelf: ^1.1.4
  stream_channel: ^2.1.0
dev_dependencies: 
  angel3_test: ^4.0.0
  angel3_pretty_logging: ^3.0.0
  shelf_static: ^1.0.0
  test: ^1.17.7
  lints: ^1.0.0
