name: angel3_mongo
version: 3.0.0
description: MongoDB-enabled services for the Angel framework. Well-tested.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/mongo
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_framework: ^4.0.0
  angel3_json_god: ^4.0.0
  angel3_merge_map: ^2.0.0
  mongo_dart: ^0.7.0
dev_dependencies:
  http: ^0.13.0
  pedantic: ^1.11.0
  test: ^1.17.0
