name: angel3_migration
version: 4.0.0
description: Database migration runtime for Angel3 ORM. Use this package to define schemas.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/orm/angel_migration
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_orm: ^4.0.0
dev_dependencies:
  pedantic: ^1.11.0
