name: angel3_migration
version: 4.0.0-beta.1
description: Database migration runtime for Angel's ORM. Use this package to define schemas.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/orm/angel_migration
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_orm: ^4.0.0-beta.1
dev_dependencies:
  pedantic: ^1.11.0
