name: angel_serialize
version: 2.2.1+2
description: Static annotations powering Angel model serialization. Combine with angel_serialize_generator for flexible modeling.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/serialize
environment:
  sdk: '>=2.0.0-dev <3.0.0'
dependencies:
  quiver_hashcode: ^2.0.0
