# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Angel3 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jobs_001:
    name: Validate framework package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "2.15.1"

      - id: angel3_framework_upgrade
        name: angel3_framework; Upgrade depedencies
        working-directory: packages/framework
        run: dart pub upgrade

      - name: angel3_framework; Verify formatting
        working-directory: packages/framework
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: angel3_framework; Analyze source code
        working-directory: packages/framework
        run: dart analyze .

      - name: angel3_framework; Run tests
        working-directory: packages/framework
        run: dart test

  jobs_002:
    name: Validate ORM packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "2.15.1"

      # Angel3 ORM
      - id: angel3_orm_upgrade
        name: angel3_orm; Upgrade depedencies
        working-directory: packages/orm/angel_orm
        run: dart pub upgrade

      - name: angel3_orm; Verify formatting
        working-directory: packages/orm/angel_orm
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: angel3_orm; Analyze source code
        working-directory: packages/orm/angel_orm
        run: dart analyze .

      # Angel3 ORM Generator
      - id: angel3_orm_generator_upgrade
        name: angel3_orm_generator; Upgrade depedencies
        working-directory: packages/orm/angel_orm_generator
        run: dart pub upgrade

      - name: angel3_orm_generator; Verify formatting
        working-directory: packages/orm/angel_orm_generator
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: angel3_orm_generator; Analyze source code
        working-directory: packages/orm/angel_orm_generator
        run: dart analyze .

      # Angel3 ORM Test
      - id: angel3_orm_test_upgrade
        name: angel3_orm_test; Upgrade depedencies
        working-directory: packages/orm/angel_orm_test
        run: dart pub upgrade

      - name: angel3_orm_test; Run orm code generator
        working-directory: packages/orm/angel_orm_test
        run: dart run build_runner build --delete-conflicting-outputs

      - name: angel3_orm_test; Verify formatting
        working-directory: packages/orm/angel_orm_test
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: angel3_orm_test; Analyze source code
        working-directory: packages/orm/angel_orm_test
        run: dart analyze .

