name: range_header
version: 3.0.0
description: Range header parser for Dart. Beyond parsing, a stream transformer is included.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/range_header
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  async: ^2.6.0
  charcode: ^1.2.0
  quiver_hashcode: ^3.0.0+1
  source_span: ^1.8.1
  string_scanner: ^1.1.0
dev_dependencies:
  #angel_framework:
  #angel_static: ^2.0.0
  file: ^6.1.0
  http_parser: ^4.0.0
  logging: ^1.0.1
  test: ^1.17.3